import {
  RestaurantVoucher,
  RestaurantOrder,
  RestaurantItem,
  InventoryItem,
  VoucherType,
} from '../types/hotel';
import {
  initialMenuItems,
  initialRestaurantOrders,
  initialInventoryItems,
} from './mockData';

export interface RestaurantDbState {
  vouchers: RestaurantVoucher[];
  orders: RestaurantOrder[];
  menuItems: RestaurantItem[];
  inventoryItems: InventoryItem[];
  cashDrawerFloat: number; // Opening cash in drawer
  lastUpdated: string;
}

export const initialRestaurantVouchers: RestaurantVoucher[] = [
  // CRV (Cash Receipt Vouchers - Incoming Cash)
  {
    id: 'v-crv-001',
    voucherNumber: 'CRV-2026-001',
    voucherType: 'CRV',
    date: '2026-10-03',
    accountHead: 'Dine-In Table Cash Collection',
    partyName: 'Table #4 & Table #2 Walk-In Guests',
    amount: 8900,
    paymentMode: 'Cash',
    referenceNo: 'POS-REC-104',
    narration: 'Cash received for Karahi & BBQ dinner sales settled at counter',
    createdBy: 'Cashier Ahmed',
    status: 'Posted',
    isAutoGenerated: false,
  },
  {
    id: 'v-crv-002',
    voucherNumber: 'CRV-2026-002',
    voucherType: 'CRV',
    date: '2026-10-04',
    accountHead: 'Advance Catering & Party Booking',
    partyName: 'Chaudhry Waqas (VIP Hall Family Dinner)',
    amount: 15000,
    paymentMode: 'Cash',
    referenceNo: 'ADV-CAT-881',
    narration: '50% advance cash deposit for upcoming 25-person family buffet',
    createdBy: 'Cashier Ahmed',
    status: 'Posted',
    isAutoGenerated: false,
  },
  {
    id: 'v-crv-003',
    voucherNumber: 'CRV-2026-003',
    voucherType: 'CRV',
    date: '2026-10-05',
    accountHead: 'Counter Takeaway Cash Sales',
    partyName: 'Takeaway Counter Customers',
    amount: 4650,
    paymentMode: 'Cash',
    referenceNo: 'POS-TKW-210',
    narration: 'Cash settled for Biryani and Tikka parcels during lunch shift',
    createdBy: 'Cashier Ahmed',
    status: 'Posted',
    isAutoGenerated: false,
  },
  {
    id: 'v-crv-004',
    voucherNumber: 'CRV-2026-004',
    voucherType: 'CRV',
    date: '2026-10-05',
    accountHead: 'Beverages & Chai Counter Cash',
    partyName: 'Tea & Cold Drinks Point',
    amount: 2800,
    paymentMode: 'Cash',
    referenceNo: 'TEA-CTR-09',
    narration: 'Evening shift cash collection for Kashmiri Chai and Mineral Water bottles',
    createdBy: 'Cashier Ahmed',
    status: 'Posted',
    isAutoGenerated: false,
  },

  // CPV (Cash Payment Vouchers - Outgoing Cash Expenses)
  {
    id: 'v-cpv-001',
    voucherNumber: 'CPV-2026-001',
    voucherType: 'CPV',
    date: '2026-10-03',
    accountHead: 'Kitchen Fresh Poultry & Meat',
    partyName: 'Al-Madina Halal Poultry Market Sukkur',
    amount: 6800,
    paymentMode: 'Cash',
    referenceNo: 'SUP-INV-441',
    narration: 'Cash payment for 8kg fresh boneless chicken & 3kg mutton handi cuts',
    createdBy: 'Chef Asghar',
    status: 'Posted',
    isAutoGenerated: false,
  },
  {
    id: 'v-cpv-002',
    voucherNumber: 'CPV-2026-002',
    voucherType: 'CPV',
    date: '2026-10-04',
    accountHead: 'Fresh Mandi Vegetables & Grocery',
    partyName: 'Subzi Mandi Sukkur (Vendor Bashir)',
    amount: 3200,
    paymentMode: 'Cash',
    referenceNo: 'MANDI-REC-12',
    narration: 'Cash paid for daily onions, ginger, garlic paste, tomatoes, lemons & mint',
    createdBy: 'Cashier Ahmed',
    status: 'Posted',
    isAutoGenerated: false,
  },
  {
    id: 'v-cpv-003',
    voucherNumber: 'CPV-2026-003',
    voucherType: 'CPV',
    date: '2026-10-04',
    accountHead: 'LPG Gas Cylinder Refill',
    partyName: 'Bolan Gas Agency Bypass',
    amount: 4500,
    paymentMode: 'Cash',
    referenceNo: 'GAS-45kg-01',
    narration: 'Emergency cash purchase of 45kg commercial LPG cylinder for kitchen tandoor',
    createdBy: 'Supervisor Farhan',
    status: 'Posted',
    isAutoGenerated: false,
  },
  {
    id: 'v-cpv-004',
    voucherNumber: 'CPV-2026-004',
    voucherType: 'CPV',
    date: '2026-10-05',
    accountHead: 'BBQ Charcoal & Commercial Ice Block',
    partyName: 'Sindh Ice & Coal Depot',
    amount: 1750,
    paymentMode: 'Cash',
    referenceNo: 'ICE-COAL-99',
    narration: '2 bags Babool charcoal for BBQ grill pit & 1 ice block for drinks chiller',
    createdBy: 'Chef Asghar',
    status: 'Posted',
    isAutoGenerated: false,
  },
  {
    id: 'v-cpv-005',
    voucherNumber: 'CPV-2026-005',
    voucherType: 'CPV',
    date: '2026-10-05',
    accountHead: 'Kitchen Dishwashing & Cleaning Petty Cash',
    partyName: 'General Store Bypass',
    amount: 850,
    paymentMode: 'Cash',
    referenceNo: 'PETTY-011',
    narration: 'Liquid dishwash, steel scrubbers, and trash liners for stewarding',
    createdBy: 'Cashier Ahmed',
    status: 'Posted',
    isAutoGenerated: false,
  },

  // JV (Journal Vouchers - Non-Cash Adjustments & Room Folio Postings)
  {
    id: 'v-jv-001',
    voucherNumber: 'JV-2026-001',
    voucherType: 'JV',
    date: '2026-10-03',
    accountHead: 'Room Folio Food Transfer',
    partyName: 'Room 105 - Kamran Khanzada (Folio #PCI-INV-2026-003)',
    amount: 5450,
    paymentMode: 'Room Folio Credit',
    referenceNo: 'KOT-DEL-089',
    narration: 'Non-cash food charge transferred to hotel room guest folio ledger upon room service delivery',
    createdBy: 'Captain Rizwan',
    status: 'Posted',
    isAutoGenerated: true,
  },
  {
    id: 'v-jv-002',
    voucherNumber: 'JV-2026-002',
    voucherType: 'JV',
    date: '2026-10-04',
    accountHead: 'Room Folio Food Transfer',
    partyName: 'Room 202 - Dr. Asad Mehmood (Folio #PCI-INV-2026-004)',
    amount: 3200,
    paymentMode: 'Room Folio Credit',
    referenceNo: 'KOT-DEL-094',
    narration: 'Breakfast & High Tea room service bill charged to in-house hotel guest room account',
    createdBy: 'Captain Rizwan',
    status: 'Posted',
    isAutoGenerated: true,
  },
  {
    id: 'v-jv-003',
    voucherNumber: 'JV-2026-003',
    voucherType: 'JV',
    date: '2026-10-05',
    accountHead: 'Kitchen Raw Stock Spoilage / Wastage',
    partyName: 'Kitchen Storage Loss Account',
    amount: 1400,
    paymentMode: 'Adjustment',
    referenceNo: 'WST-LOG-04',
    narration: 'Debit Food Spoilage Expense / Credit Raw Material Stock for curdled milk & damaged produce during power outage',
    createdBy: 'Executive Chef',
    status: 'Posted',
    isAutoGenerated: false,
  },
  {
    id: 'v-jv-004',
    voucherNumber: 'JV-2026-004',
    voucherType: 'JV',
    date: '2026-10-05',
    accountHead: 'VIP Courtesy & Manager Complimentary Discount',
    partyName: 'Sukkur IBA Faculty Official Dinner Table #7',
    amount: 2100,
    paymentMode: 'Adjustment',
    referenceNo: 'COMP-VIP-02',
    narration: '20% corporate courtesy dining discount approved by General Manager',
    createdBy: 'Manager Rashid',
    status: 'Posted',
    isAutoGenerated: false,
  },
  {
    id: 'v-jv-005',
    voucherNumber: 'JV-2026-005',
    voucherType: 'JV',
    date: '2026-10-05',
    accountHead: 'Credit Vendor Purchase (Accounts Payable)',
    partyName: 'Al-Madina Rice Traders Sukkur',
    amount: 22800,
    paymentMode: 'Adjustment',
    referenceNo: 'CR-BILL-908',
    narration: 'Credit purchase of 60kg Super Kernel Basmati Rice on 30-day supplier credit terms',
    createdBy: 'Accountant Zahid',
    status: 'Posted',
    isAutoGenerated: false,
  },
];

const DB_STORAGE_KEY = 'pci_restaurant_dummy_db_v1';

export function getInitialDbState(): RestaurantDbState {
  return {
    vouchers: initialRestaurantVouchers,
    orders: initialRestaurantOrders,
    menuItems: initialMenuItems,
    inventoryItems: initialInventoryItems.filter(
      (i) => i.category === 'Kitchen Ingredients' || i.category === 'Beverages & Soft Drinks'
    ),
    cashDrawerFloat: 15000, // PKR opening cash float
    lastUpdated: new Date().toISOString(),
  };
}

export const dummyDb = {
  // Load entire DB state (from localStorage or initial defaults)
  loadState(): RestaurantDbState {
    if (typeof window === 'undefined') {
      return getInitialDbState();
    }
    try {
      const stored = localStorage.getItem(DB_STORAGE_KEY);
      if (stored) {
        const parsed = JSON.parse(stored) as RestaurantDbState;
        // Ensure structure validity
        if (Array.isArray(parsed.vouchers) && Array.isArray(parsed.orders)) {
          return parsed;
        }
      }
    } catch (e) {
      console.warn('Could not read from localStorage, using default DB state:', e);
    }
    const initial = getInitialDbState();
    this.saveState(initial);
    return initial;
  },

  // Save entire DB state
  saveState(state: RestaurantDbState): void {
    if (typeof window === 'undefined') return;
    try {
      state.lastUpdated = new Date().toISOString();
      localStorage.setItem(DB_STORAGE_KEY, JSON.stringify(state));
    } catch (e) {
      console.error('Failed to save DB state to localStorage:', e);
    }
  },

  // Reset to initial dummy demo data
  resetToDefault(): RestaurantDbState {
    const fresh = getInitialDbState();
    this.saveState(fresh);
    return fresh;
  },

  // Get all vouchers
  getVouchers(): RestaurantVoucher[] {
    return this.loadState().vouchers;
  },

  // Add a new voucher (CRV, CPV, JV)
  addVoucher(
    voucherData: Omit<RestaurantVoucher, 'id' | 'voucherNumber'> & { customVoucherNumber?: string }
  ): RestaurantVoucher {
    const state = this.loadState();
    const countByType = state.vouchers.filter((v) => v.voucherType === voucherData.voucherType).length + 1;
    const autoNumber = `${voucherData.voucherType}-2026-${String(countByType).padStart(3, '0')}`;

    const newVoucher: RestaurantVoucher = {
      id: `v-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      voucherNumber: voucherData.customVoucherNumber || autoNumber,
      voucherType: voucherData.voucherType,
      date: voucherData.date || new Date().toISOString().slice(0, 10),
      accountHead: voucherData.accountHead,
      partyName: voucherData.partyName,
      amount: Number(voucherData.amount) || 0,
      paymentMode: voucherData.paymentMode || 'Cash',
      referenceNo: voucherData.referenceNo || '',
      narration: voucherData.narration || '',
      createdBy: voucherData.createdBy || 'Staff',
      status: voucherData.status || 'Posted',
      isAutoGenerated: voucherData.isAutoGenerated || false,
    };

    state.vouchers = [newVoucher, ...state.vouchers];
    this.saveState(state);
    return newVoucher;
  },

  // Delete a voucher by ID
  deleteVoucher(voucherId: string): boolean {
    const state = this.loadState();
    const prevCount = state.vouchers.length;
    state.vouchers = state.vouchers.filter((v) => v.id !== voucherId);
    if (state.vouchers.length !== prevCount) {
      this.saveState(state);
      return true;
    }
    return false;
  },

  // Bulk Import vouchers (e.g. from CSV or external system)
  importVouchers(
    incomingVouchers: Array<Partial<RestaurantVoucher> & { voucherType: VoucherType; amount: number; narration: string }>
  ): { count: number; imported: RestaurantVoucher[] } {
    const state = this.loadState();
    const imported: RestaurantVoucher[] = [];

    incomingVouchers.forEach((item, index) => {
      const vType: VoucherType = item.voucherType || 'CRV';
      const countByType = state.vouchers.length + imported.length + index + 1;
      const vNumber =
        item.voucherNumber || `${vType}-2026-IMP-${String(countByType).padStart(3, '0')}`;

      const newV: RestaurantVoucher = {
        id: `imp-v-${Date.now()}-${index}`,
        voucherNumber: vNumber,
        voucherType: vType,
        date: item.date || new Date().toISOString().slice(0, 10),
        accountHead: item.accountHead || `${vType} General Account Head`,
        partyName: item.partyName || 'General Party / Counter',
        amount: Math.abs(Number(item.amount)) || 0,
        paymentMode:
          item.paymentMode ||
          (vType === 'JV' ? 'Adjustment' : 'Cash'),
        referenceNo: item.referenceNo || 'BULK-IMPORT',
        narration: item.narration || `Imported ${vType} transaction`,
        createdBy: item.createdBy || 'Data Import',
        status: item.status || 'Posted',
        isAutoGenerated: false,
      };

      imported.push(newV);
    });

    state.vouchers = [...imported, ...state.vouchers];
    this.saveState(state);
    return { count: imported.length, imported };
  },

  // Auto-sync / Auto-import completed POS orders into vouchers
  autoSyncOrdersToVouchers(orders: RestaurantOrder[]): { newCrvCount: number; newJvCount: number } {
    const state = this.loadState();
    const existingRefNos = new Set(
      state.vouchers.map((v) => v.referenceNo).filter(Boolean)
    );

    let newCrvCount = 0;
    let newJvCount = 0;
    const newVouchers: RestaurantVoucher[] = [];

    orders.forEach((order) => {
      if (existingRefNos.has(order.orderNumber)) {
        return; // Already recorded
      }

      if (order.paymentStatus === 'Cash Settled') {
        // Cash order -> Auto CRV (Cash Receipt Voucher)
        newCrvCount++;
        const crvCount =
          state.vouchers.filter((v) => v.voucherType === 'CRV').length + newCrvCount;
        newVouchers.push({
          id: `auto-crv-${order.id}`,
          voucherNumber: `CRV-2026-${String(crvCount).padStart(3, '0')}`,
          voucherType: 'CRV',
          date: new Date().toISOString().slice(0, 10),
          accountHead: 'Restaurant Food Sales (Cash)',
          partyName: `${order.guestName} (${order.tableOrRoom})`,
          amount: order.totalAmount,
          paymentMode: 'Cash',
          referenceNo: order.orderNumber,
          narration: `POS Order ${order.orderNumber} for ${order.tableOrRoom} settled via Cash`,
          createdBy: 'POS System Auto-Post',
          status: 'Posted',
          isAutoGenerated: true,
        });
      } else if (order.paymentStatus === 'Billed to Room Folio' || order.roomNumber) {
        // Room Folio order -> Auto JV (Journal Voucher)
        newJvCount++;
        const jvCount =
          state.vouchers.filter((v) => v.voucherType === 'JV').length + newJvCount;
        newVouchers.push({
          id: `auto-jv-${order.id}`,
          voucherNumber: `JV-2026-${String(jvCount).padStart(3, '0')}`,
          voucherType: 'JV',
          date: new Date().toISOString().slice(0, 10),
          accountHead: 'Room Folio Food Transfer (Receivable)',
          partyName: `${order.guestName} (Room ${order.roomNumber || order.tableOrRoom})`,
          amount: order.totalAmount,
          paymentMode: 'Room Folio Credit',
          referenceNo: order.orderNumber,
          narration: `Food bill of POS Order ${order.orderNumber} transferred to In-House Guest Room Folio`,
          createdBy: 'POS System Auto-Post',
          status: 'Posted',
          isAutoGenerated: true,
        });
      }
    });

    if (newVouchers.length > 0) {
      state.vouchers = [...newVouchers, ...state.vouchers];
      this.saveState(state);
    }

    return { newCrvCount, newJvCount };
  },

  // Save new restaurant order
  addOrder(order: RestaurantOrder): RestaurantDbState {
    const state = this.loadState();
    state.orders = [order, ...state.orders];
    this.saveState(state);
    return state;
  },

  // Update order status
  updateOrderStatus(orderId: string, status: RestaurantOrder['status']): RestaurantDbState {
    const state = this.loadState();
    state.orders = state.orders.map((o) => (o.id === orderId ? { ...o, status } : o));
    this.saveState(state);
    return state;
  },

  // Financial summary of restaurant vouchers
  getFinancialSummary() {
    const vouchers = this.getVouchers();
    const crvTotal = vouchers
      .filter((v) => v.voucherType === 'CRV' && v.status === 'Posted')
      .reduce((sum, v) => sum + v.amount, 0);

    const cpvTotal = vouchers
      .filter((v) => v.voucherType === 'CPV' && v.status === 'Posted')
      .reduce((sum, v) => sum + v.amount, 0);

    const jvTotal = vouchers
      .filter((v) => v.voucherType === 'JV' && v.status === 'Posted')
      .reduce((sum, v) => sum + v.amount, 0);

    const netCashDrawer = crvTotal - cpvTotal;

    return {
      totalCrv: crvTotal,
      totalCpv: cpvTotal,
      totalJv: jvTotal,
      netCashDrawer,
      totalVoucherCount: vouchers.length,
    };
  },
};

